### ISSUE TITLE
Floorspace.js editor is using polygon tool if I select the rectangle tool

### ISSUE THREAD

**Issue by rwadhwa910** [openstudiocoalition/OpenStudioApplication#189] opened 2020-07-09 19:07 UTC
**Issue overview**

If I try to use the eraser tool in the editor tab and after that I switch to rectangle tool, Although the rectangle tool will be active but the operations performed in the editor will be of polygon.

**Current Behavior**

In the image below You can see I have selected the rectangle tool but the operations are performed similar to polygon tool. 
This is happening only when I switch to rectangle after using eraser tool.

Also web version of floor space does not have this issue.

![Polygon](https://user-images.githubusercontent.com/63880759/87080503-0263fc00-c1e5-11ea-926e-07e2c820d8d6.PNG)

 **Expected Behavior**

It should perform the tasks that should be performed by rectangle tool.

**Steps to Reproduce**
1. Make a floorplan in geometry editor tab in Openstudio.
2. Use eraser tool to delete some spaces.
3. Use Rectangle tool to draw a new space.
4. Instead of rectangle tool, the polygon tool will be active.

**Environment**

Windows 10.

Open studio App Version 1.0.1
Open studio Version 3.0.1

**Comment by macumber** [comment] 2021-07-22 04:18
This seems like a duplicate of https://github.com/NREL/floorspace.js/issues/377

**Closed by macumber** 2021-07-22 04:18 UTC
Labels: Triage
