### ISSUE TITLE
Text in OpenStudio Results HTML viewed in app appears white on Windows Machine

### ISSUE THREAD

**Issue by DavidGoldwasser** [openstudiocoalition/OpenStudioApplication#328] opened 2021-04-06 19:30 UTC
Issue overview
--------------
https://unmethours.com/question/52134/report-text-is-white/?comment=53816#post-id-53816
## Current Behavior

User reports changing between light and dark mode doesn't impact this, and viewing the file in web browser outside of OpenStudio Application doesn't exhibit this issue.

## Possible Solution
I'm wondering if fix to support issue #203 could have changed viewing of HTML reports?, although that was a mac issue, not windows.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Window 10 Home 20H2 
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.1.0

**Comment by ARCHI-JIN** [comment] 2021-04-09 00:52
Thanks for David! And I add the picture for this bug now.[2021-04-07 005153](https://user-images.githubusercontent.com/50307499/114113191-a7e10300-9910-11eb-869c-2a6bba389901.jpg)

**Comment by jmarrec** [comment] 2021-05-26 17:01
I can't reproduce. @chrisbalbach tested with windows 10 and openstudio 1.1.0+b2e7010aa0 and it worked fine. I'm closing, but if you have more info to give to help reproduce I'm happy to reopen. Thanks!

**Closed by jmarrec** 2021-05-26 17:01 UTC
Labels: Triage

**Comment by macumber** [comment] 2021-05-27 02:56
@ARCHI-JIN were you using dark mode by any chance?

**Comment by jmarrec** [comment] 2021-05-31 10:55
@macumber He said in a comment on https://unmethours.com/question/52134/report-text-is-white/?comment=53816#post-id-53816  that switching between black and white modes didn't help. It's not clear if the change was done WHILE the app was running or not though.
