### ISSUE TITLE
Zone level PTHP does not connect nodes

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#324] opened 2021-03-21 18:46 UTC
Issue overview
--------------
 When I try to apply a zone level packaged terminal heat pump, OS does not connect recognize the control zone or connect the zone nodes.

## Steps to Reproduce

1. Create Model
2. Insert PTHP into Zone Equipment
3. Run simulation
4.
![2021-03-21_E](https://user-images.githubusercontent.com/69771412/111917013-f6e6f700-8a3a-11eb-95f7-cf8edc586424.jpg)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
![2021-03-21 (2)](https://user-images.githubusercontent.com/69771412/111917076-3f9eb000-8a3b-11eb-9261-afab3ac64ab5.png)

 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment] 2021-06-01 07:32
I doubt the error message you are showing us has nothng to do with the PTHP. the PTHP does not involve SPM:SingleZone:Reheat whatsoever. I have added a PTHP to the exampleModel() and the simulation ran just fine with v1.2.0-rc6


I'm going to close this, but I'm happy to reopen if I can get something reproducible.

**Closed by jmarrec** 2021-06-01 07:32 UTC
Labels: Triage

**Comment by Ski90Moo** [comment] 2021-06-01 16:06
Ok, sorry for the trouble. You are correct. I also cannot reproduce it.  I must have had some undeleted objects in my model, not related to the PTHP.

**Comment by jmarrec** [comment] 2021-06-02 05:51
@Ski90Moo no problem at all. The separation between App and SDK is new and it is sometimes hard to tell where a problem is coming from. And as models are complex, it's also sometimes hard to know what caused what. I appreciate the detailed bug report, thank you for that. I didn't have to go chasing far since it had all the information needed and that's a time saver!
