### ISSUE TITLE
Make the right-hand pane on Schedules editable

### ISSUE THREAD

**Issue by LouYingli** [openstudiocoalition/OpenStudioApplication#286] opened 2020-12-14 21:33 UTC
Enhancement Request
--------------

Make the right-hand pane on Schedules editable.
## Detailed Description

The right-hand pane on Schedules cannot be edited. In some applications, such as large-scale simulations, users would need to edit them.
![image](https://user-images.githubusercontent.com/52507951/102138224-448b0c80-3e19-11eb-9655-bde7c2c2368f.png)

**Comment by macumber** [comment] 2020-12-19 20:02
I think this is a duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/271, do you agree @LouYingli ?

**Comment by LouYingli** [comment] 2020-12-20 03:39
I think this is not a duplicate of #271. #271 suggests that the right-hand pane on Schedules is in read-only mode. I think that's why I can't edit the right-hand pane on Schedules now. I have a different opinion with #271. I think we should make the right-hand pane on Schedules editable.

**Comment by macumber** [comment] 2020-12-23 19:08
The values displayed in the right hand pane under edit on the schedules tab are the day schedule values that are editable in the main gui area.  The values in the right hand pane are not editable because we would have to redraw the schedule view in the main gui every time one of those values changed.  Also we would have to support adding and deleting values from the day schedule in the right hand pane.  So those values are intentionally read only on that tab.

**Comment by LouYingli** [comment] 2020-12-30 19:05
Thank you for the clarification. I agree that the _Schedule Type Limits Name, Interpolate to Timestop, Hour, Minute,_  and _Value Until Time_ in the right-hand pane do not need to be editable. Because we can edit this information in the main gui area. But the _Name_ of the _ScheduleDay_ should be editable. For example, as shown in the following figure, the _Name_ of the _ScheduleDay_ is "Schedule Day 2".  I want to modify the _Name_ of the _ScheduleDay_ as "Office Bldg Occ Sat Day". But I cannot modify it in the OS app.
 
![image](https://user-images.githubusercontent.com/52507951/103374566-2407b700-4a95-11eb-88ca-cec8744b273f.png)

**Comment by macumber** [comment] 2020-12-31 22:39
Oh ok, I see, thanks for clarifying.  Yes, editing the name of the day schedule seems reasonable.  Would it meet your needs if we just did that on the schedule editing tab and not in the edit/inspector?

**Comment by LouYingli** [comment] 2020-12-31 23:04
Sorry. What is the schedule editing tab refer to? Do you mean the left-hand pane (in the following figure)? I think it may be easier to make the _Name_ of the _ScheduleDay_ in the right-hand-pane editable.
![image](https://user-images.githubusercontent.com/52507951/103430454-850cb900-4b81-11eb-868a-2a5dc9538825.png)

**Comment by macumber** [comment] 2020-12-31 23:32
I'd suggest adding it right on top of the day schedule that is being edited

![image](https://user-images.githubusercontent.com/1327850/103430855-9d7ed280-4b85-11eb-8729-a2b5b1fe9489.png)

**Comment by LouYingli** [comment] 2020-12-31 23:41
I see. It's a very good option.

**Closed** 2021-05-28 07:09 UTC
Labels: Enhancement Request
