### ISSUE TITLE
OS:SpaceInfiltration:DesignFlowRate edit panel displays wrong units

### ISSUE THREAD

**Issue by souliane** [openstudiocoalition/OpenStudioApplication#272] opened 2020-11-13 11:49 UTC
Issue overview
--------------
OS:SpaceInfiltration:DesignFlowRate edit panel displays wrong units for "Flow per Space Floor Area" and "Flow per Exterior Surface Area".

## Current Behavior
The displayed unit for the fields that are mentioned above is m/s.

## Expected Behavior
It should be m3/s-m2 instead.

### Environment
Windows 10 Home
OpenStudioApplication 1.1.0

**Comment by macumber** [comment] 2020-11-24 18:36
This is a known issue with the OpenStudio units engine.  Basically it simplifies (m^3)/(s*m^2) to m/s.

**Comment by jmarrec** [comment] 2024-10-14 12:07
Duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/152

**Closed by jmarrec** 2024-10-14 12:07 UTC
Labels: severity - Minor Bug :baby_chick:
