### ISSUE TITLE
Selecting / unselecting boolean arguments for a measure doesn't change UI

### ISSUE THREAD

**Issue by corymosiman12** [openstudiocoalition/OpenStudioApplication#283] opened 2020-12-02 19:33 UTC
Issue overview
--------------
Selecting / unselecting boolean arguments for a measure doesn't change UI, although argument does change in the workflow.osw

## Current Behavior
Above.

## Expected Behavior
The UI and the OSW should be in alignment for boolean arguments.

## Steps to Reproduce

1. Occurs in both the Apply Measure Now and in the Measures screens.

### Environment
- MacOS 10.14.6
- OS App Version 1.1.0+b2e7010aa0

[Archive.zip](https://github.com/openstudiocoalition/OpenStudioApplication/files/5631594/Archive.zip)

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/28991233/100922004-4f55b100-34ab-11eb-8e95-bcbe8bef786d.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/28991233/100922006-4fee4780-34ab-11eb-8531-8b79b72079b8.png)

**Comment by macumber** [comment] 2021-05-29 18:40
Duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/85

**Closed by macumber** 2021-05-29 18:40 UTC
Labels: Triage
