### ISSUE TITLE
Openstudio application crashes after clicking on thermal zone tab

### ISSUE THREAD

**Issue by Nischal0150** [openstudiocoalition/OpenStudioApplication#554] opened 2022-06-27 03:45 UTC
Issue overview
--------------
I am using Openstudio 3.40 to model a building with 50 thermal zones. But every time I click on the thermal zone tab on Openstudio, the application stalls for a few seconds and then crashes abruptly.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): windows 10
 - Version of OpenStudioApplication 1.4

**Comment by macumber** [comment] 2022-06-27 04:08
Moved from https://github.com/NREL/OpenStudio/issues/4617

@Nischal0150 Would you be able to post the model here (you can rename it to a .txt extension and upload it to the issue) or send it privately to osc@openstudiocoalition.org?

**Comment by Nischal0150** [comment] 2022-06-27 04:16
> Moved from [NREL/OpenStudio#4617](https://github.com/NREL/OpenStudio/issues/4617)
> 
> @Nischal0150 Would you be able to post the model here (you can rename it to a .txt extension and upload it to the issue) or send it privately to [osc@openstudiocoalition.org](mailto:osc@openstudiocoalition.org)?

I have sent the model to osc@openstudiocoalition.org

**Comment by macumber** [comment] 2022-06-28 05:37
Thanks @Nischal0150, I can reproduce the crash. I think this has something to do with `NUM_ROWS_PER_GRIDLAYOUT` which is currently set at 50.

**Comment by macumber** [comment] 2022-06-28 05:56
Another odd thing seems to be that the ThermalZones are missing an inletPortList, was this OSM created through some script or other process?  Did it use the OS SDK to create the ThermalZone objects?

**Comment by macumber** [comment] 2022-06-28 05:59
Possibly related to https://github.com/openstudiocoalition/OpenStudioApplication/issues/554

**Comment by Nischal0150** [comment] 2022-06-28 06:09
> 

Yes, the thermal zones were created through openstudio user script using openstudio sketchup plugin V 1.4.0

**Comment by macumber** [comment] 2022-06-29 02:32
Hmm, I was not able to reproduce this using SketchUp 2021 on Windows 11, OpenStudio SketchUp Plug-in 1.4.0, OpenStudio Application 1.4.0, and OpenStudio SDK 1.4.0

![image](https://user-images.githubusercontent.com/1327850/176338434-0f3ff4aa-ca8f-4291-b9f9-89a038ce086f.png)

Can you check your OpenStudio SketchUp Plug-in preferences to make sure that you have the plug-in pointed at the right OpenStudio Application version?

![image](https://user-images.githubusercontent.com/1327850/176337965-c03dc2c6-7bdb-42eb-b356-97e40d798215.png)

**Comment by macumber** [comment] 2022-12-30 01:45
I can't reproduce this (by making a new model in the SketchUp Plug-in and running the "Add New Thermal Zone For Spaces With No Thermal Zone" user script with 1.5.0-rc.1 either.  I'm going to close this issue, we can re-open it if we know how the zones were created without the necessary port objects.  The code in the OS ThermalZone constructor hasn't changed for 7 years.

**Comment by lutareeem** [comment] 2023-08-28 09:05
Windows 10
OS Application 1.2.1
OS 3.6.1

Same thing is happening - click on a group to change thermal zone, it gives me this: 

RuntimeError
bad allocation
BACKTRACE:
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `setIddObjectType'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/DialogManager.rb:321:in `selection_changed'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/interfaces/MaterialsInterface.rb:374:in `rendering_mode='
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/dialogs/SpaceAttributesInterface.rb:238:in `block in <module:OpenStudio>'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:262:in `block in process_events'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:255:in `each'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:255:in `process_events'
C:/Users/admin/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/openstudio/lib/PluginManager.rb:318:in `block in start_event_processing'

And when I click on Thermal Zones in the Inspector it crashes. I've tried different versions and I'm still getting it?

**Comment by macumber** [comment] 2023-09-02 17:17
@lutareeem are you using the same model as before?  Do your ThermalZone objects have valid `Zone Air Inlet Port List` and `Zone Air Exhaust Port List` fields?

Here is a ThermalZone from the last example model I got from you in a text editor:
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/bea9ad12-8e7b-46b4-b2c5-21775e2d5940)

Here is a ThermalZone from a correct model for reference:
![image](https://github.com/openstudiocoalition/OpenStudioApplication/assets/1327850/5e85b4b0-6cb2-43ca-be0c-1dc6fe3ce460)

**Comment by macumber** [comment] 2023-09-09 18:51
Re-closing until we get more information

**Closed by macumber** 2023-09-09 18:51 UTC
Labels: severity - Normal Bug :bug:, resolution - Can't Reproduce :grey_question:
