### ISSUE TITLE
GridView is completely blank on Spaces and Thermal Zones tabs for large model

### ISSUE THREAD

**Issue by MatthewSteen** [openstudiocoalition/OpenStudioApplication#387] opened 2021-06-22 03:01 UTC
Issue overview
--------------
GridView is completely blank on the Space and Thermal Zones tabs for a large (200 Space/ThermalZone) model in 1.2.0 on Windows (will test Linux). The tabs do seem to load faster than previous versions though 😃 

[in.zip.txt](https://github.com/openstudiocoalition/OpenStudioApplication/files/6690690/in.zip.txt)

## Current Behavior
__Spaces__
![image](https://user-images.githubusercontent.com/8397034/122856170-95e9ec00-d2d3-11eb-947c-d665db8ce318.png)

__Thermal Zones__
![image](https://user-images.githubusercontent.com/8397034/122855952-42779e00-d2d3-11eb-898d-897b05531d70.png)

## Steps to Reproduce

1. Model was created with [NREL/gbxml-to-openstudio (private)](https://github.com/NREL/gbxml-to-openstudio).
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.2.0

**Comment by macumber** [comment] 2021-06-22 03:14
Thanks @MatthewSteen, the example model is very helpful but I am going to close this as a duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/378

I do hope to get to this issue in a patch release

**Closed by macumber** 2021-06-22 03:14 UTC
Labels: Triage

**Comment by macumber** [comment] 2021-06-22 03:20
I can reproduce with this model FWIW

**Comment by MatthewSteen** [comment] 2021-06-22 03:26
Thanks @macumber , sorry for the dup!
