### ISSUE TITLE
Incorrect SwimmingPool:Indoor field unit

### ISSUE THREAD

**Issue by antoine-galataud** [openstudiocoalition/OpenStudioApplication#591] opened 2023-02-01 10:47 UTC
Issue overview
--------------

Incorrect unit displayed for "Pool Miscellaneous Equipment Power" field of a SwimmingPool:Indoor object. Currently displays Pa, but should be W·m³/s according to EnergyPlus documentation.

![osa_pool_eq_pw_bug](https://user-images.githubusercontent.com/5330926/216021643-9423f06a-e23d-45a8-b627-8718d0fe30f5.png)

### Environment

 - Platform (Operating system, version): Ubuntu 20.04 LTS
 - Version of OpenStudioApplication: 1.5.0

**Comment by jmarrec** [comment] 2023-03-31 12:43
Duplicate of #152. That's how the Unit converter works... `W-s/m3` reduces down to `Pa`.

**Closed** 2023-03-31 12:45 UTC
Labels: resolution - Duplicate
