### ISSUE TITLE
Bool button doesn't display on Apply Measure Now measure argument

### ISSUE THREAD

**Issue by DavidGoldwasser** [openstudiocoalition/OpenStudioApplication#85] opened 2020-03-17 20:07 UTC
Issue overview
--------------
Bool arguments display as checked whether that argument default value is true of false. There is no way to change the visible state to false. I had not confirmed if this is a display issue or function issue yet.

## Current Behavior
In prior version of OpenStudio Application this functioned. Bool could be changed by clicking and it read in the default value from the measure.

Bool doesn't function.

<img width="773" alt="Screen Shot 2020-03-17 at 2 04 30 PM" src="https://user-images.githubusercontent.com/4857055/76897157-d4833200-6858-11ea-8600-5bcc2eba22f1.png">

## Expected Behavior

Bool args should function both in Apply Measures now and on Measures tab.

## Steps to Reproduce

Load any measure with bool argument into Apply Measures Now

## Possible Solution

I expect this is related to QT dependency upgrade from older OpenStudio application.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

### Context

Functional limitation to use of Apply Measures now that should be fixed before final release.

**Comment by DavidGoldwasser** [comment] 2020-03-17 20:08
CC: @tijcolem

**Comment by jmarrec** [comment] 2020-03-23 13:36
@DavidGoldwasser Does it work on the "Measures" Tab?

**Comment by DavidGoldwasser** [comment] 2020-03-23 14:33
@jmarrec no, I see the same behavior there.

**Comment by jmarrec** [comment] 2020-03-23 14:33
It works on both Apply Now and Measures Tab with my loal build on Ubuntu... What OS are you using? which installer?

**Comment by jmarrec** [comment] 2020-03-23 14:35
![85_BoolArgument](https://user-images.githubusercontent.com/5479063/77327731-eb73c980-6d1b-11ea-8130-297494d64ae8.gif)

**Comment by DavidGoldwasser** [comment] 2020-03-23 17:55
@jmarrec I confirmed this still happens with latest version of OS App using 3.x for mac that I got from @tijcolem 

<img width="416" alt="Screen Shot 2020-03-23 at 11 54 10 AM" src="https://user-images.githubusercontent.com/4857055/77347253-2dd9de00-6cfd-11ea-94ae-731312802cc8.png">

**Comment by jmarrec** [comment] 2020-04-07 15:19
@DavidGoldwasser Have you tried the openstudioapplication-1.0.0-rc1 installer?

**Comment by DavidGoldwasser** [comment] 2020-04-14 20:21
@jmarrec yes, it still had this issue

**Comment by macumber** [comment] 2020-09-15 04:12
I could not reproduce this in v1.0.1, uploaded a measure to the issues repo

**Comment by DavidGoldwasser** [comment] 2020-11-16 18:19
@macumber did this get in 1.1.0? I still see this behavior on Mac.

**Comment by macumber** [comment] 2021-05-17 02:42
I think this was a styling issue, the button was working (in that the value in the JSON was changed) but the appearance on the app didn't change.  I think this is fixed in 1.2.0-RC1.

**Closed** 2021-05-28 21:11 UTC
Labels: severity - Major Bug :boom:
