### ISSUE TITLE
GBXML import does not show spaces in App

### ISSUE THREAD

**Issue by Ski90Moo** [openstudiocoalition/OpenStudioApplication#394] opened 2021-07-02 17:55 UTC
Issue overview
--------------
After importing a gbxml file, the spaces do not show up on the spaces tab:
![UTlzN4jbtm](https://user-images.githubusercontent.com/69771412/124312216-cfb4c100-db23-11eb-9fed-68df019c5c44.gif)

## Steps to Reproduce

1. Here is the gbxml file: https://www.dropbox.com/s/4n989bo4tdbf0kg/HEP-21-06%20Skp_008_Metric-Load%20%281%29.xml?dl=0
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
![2021-07-02](https://user-images.githubusercontent.com/69771412/124312267-dd6a4680-db23-11eb-9e4a-58f1347ea062.png)

**Comment by Ski90Moo** [comment] 2021-07-02 19:01
The import works fine if I use the OS App version 1.1.0

**Comment by macumber** [comment] 2021-07-03 00:25
Thanks for the report, I believe this is a duplicate of https://github.com/openstudiocoalition/OpenStudioApplication/issues/378

There are some test installers linked on #378 that you could test, it worked for me using https://github.com/openstudiocoalition/OpenStudioApplication/suites/3140320824/artifacts/72124251

**Closed by macumber** 2021-07-03 00:25 UTC
Labels: Triage

**Comment by Ski90Moo** [comment] 2021-07-14 01:53
Ok, that works.
