### ISSUE TITLE
Windows Defender warning comes up when the installer is run

### ISSUE THREAD

**Issue by DaveInCaz** [openstudiocoalition/OpenStudioApplication#248] opened 2020-10-08 11:40 UTC
Issue overview
--------------
When running the OS application installer it shows a dire-looking warning.

## Current Behavior

![image](https://user-images.githubusercontent.com/18285074/95453648-3e6c4180-0939-11eb-97ad-de97b28877f2.png)

## Expected Behavior
It should run without this warning.

## Steps to Reproduce
Download & run the 1.0.1 installer on Windows 10

## Possible Solution
Code sign the installer?

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Win10 x64
 - Version of OpenStudioApplication (if using an intermediate build, include SHA): 1.0.1

**Comment by jmarrec** [comment] 2020-10-08 14:17
Duplicate of #205, but thanks for reporting it. We're aware of this. But it requires a code signing certificate, which you obviously have to pay a significant amount of money for, so it's not high on the list of priorities.

**Closed by jmarrec** 2020-10-08 14:17 UTC
Labels: Triage

**Comment by DaveInCaz** [comment] 2020-10-08 15:02
@jmarrec oops, sorry I hadn't realized it was a dupe! Thanks

**Comment by macumber** [comment] 2020-10-09 05:34
Thanks for the report @DaveInCaz we are hopeful that the OpenStudio Coalition will be able to get the certificates set up for future releases.  In the mean time please help us by submitting the app as safe, once Windows defender get's enough people saying an app is ok then they lower the level of warnings about it.
